"""update cuscade

Revision ID: 42d5a76f0536
Revises: 949bd590a6fb
Create Date: 2025-03-27 12:18:14.654824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d5a76f0536'
down_revision = '949bd590a6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_ticket_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_ticket_id_fkey', 'tickets', ['ticket_id'], ['id'])

    # ### end Alembic commands ###
